config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: 'dashboard#index'
    get :dashboard, to: 'dashboard#index', as: :dashboard
    resources :categories
    resources :users
    resource :profile do
      get 'edit_password'
      post 'update_password'
    end
    get 'signin', to: 'sessions#new', as: :signin
    post 'signin', to: 'sessions#create'
    get 'signout', to: 'sessions#destroy', as: :signout
    get 'errors/403', to: 'errors#error_403', as: :error_403
    resources :errors
    get '*not_found', to: 'errors#error_404'
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/concerns/trashable.rb
module Trashable extend ActiveSupport::Concern
  included do
    default_scope where(trashed: false)
    scope :trashed, -> { where(trashed: true) }
  end

  def trash
    update(trashed: true)
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  scope :by_user, ->(user_id) { where(user_id: user_id) }
  scope :unread, -> { where(read: false) }
  scope :read, -> { where(read: true) }
  scope :sorted, -> { order(read: :asc, created_at: :desc) }
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/stock.rb
class Stock < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  RoleEmployee, RoleManager = 1, 2
  attr_accessor :password, :password_confirmation

  has_many :notifications

  before_create :encrypt_password_and_set_token

  validates :account, presence: true, length: { maximum: 32 }
  validates :password, presence: true, length: { maximum: 50 }, on: :create
  validates :name, presence: true, length: { maximum: 50 }
  validates :role, presence: true

  def encrypt_password_and_set_token
    self.hashed_password = Digest::MD5.hexdigest(self.password)
    self.token = SecureRandom.urlsafe_base64
  end

  def authenticate password
    self.hashed_password == Digest::MD5.hexdigest(password) ? self : nil
  end

  def update_password password
    self.update(hashed_password: Digest::MD5.hexdigest(password))
  end
end

app/controllers/admin/base_controller.rb
# -*- encoding : utf-8 -*-
class Admin::BaseController < ApplicationController
  layout 'admin'

  before_filter :authenticate
  before_filter :find_notifications

  unless Rails.application.config.consider_all_requests_local
    rescue_from Exception, with: lambda { |exception| render_error 500, exception }
    rescue_from ActionController::RoutingError, ActionController::UnknownController, ::AbstractController::ActionNotFound, ActiveRecord::RecordNotFound, with: lambda { |exception| render_error 404, exception }
  end

  protected
  def render_error status, exception
    #Error.create(caller: "Administrator-#{session[:user][:id]}", name: exception.class.to_s, message: exception.message, backtrace: "<p>#{exception.backtrace.try(:join, '</p><p>')}</p>")
    render template: "errors/error_#{status}", status: status
  end
  
  def authenticate
    if session[:user].blank?
      redirect_to admin_signin_path
    else
      
    end
  end
  
  def find_notifications
    @unread_notifications_count = Notification.by_user(session[:user][:id]).unread.count
    @unread_notifications_count = '99+' if @unread_notifications_count > 99
    @dropdown_notifications = Notification.by_user(session[:user][:id]).unread.sorted.limit(5)
  end

  def convert_picker_string_to_time time
    "#{time}".to_datetime - 8.hours
  end

  def convert_picker_to_datetime date, time
    "#{date} #{time}".to_datetime - 8.hours
  end
end

app/controllers/admin/dashboard_controller.rb
# -*- encoding : utf-8 -*-
class Admin::DashboardController < Admin::BaseController

  def index

  end
end

app/controllers/admin/sessions_controller.rb
# -*- encoding : utf-8 -*-
class Admin::SessionsController < Admin::BaseController
  skip_before_filter :authenticate, :find_notifications
  layout null: true

  def create
    user = User.where(account: params[:account]).first.try(:authenticate, params[:password])
    unless user.blank?
      if user.available?
        user.update(last_signined_at: user.current_signined_at, current_signined_at: Time.now)
        session[:user] = { id: user.id, role: user.role, name: user.name, last_signined_at: user.last_signined_at }
        redirect_to admin_dashboard_path
      else
        redirect_to admin_signin_path, alert: '账号被禁用，无法登录'
      end
    else
      redirect_to admin_signin_path, alert: '账号或密码错误，请检查后重试'
    end
  end

  def destroy
    session[:user] = nil
    redirect_to admin_signin_path
  end
end

app/controllers/admin/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < BaseController
  
  def index
    @users = User.paginate page: params[:page]
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: '创建成功！'
    else
      render action: 'new'
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user, notice: '更新成功！'
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  protected
  def user_params
    params.require(:user).permit(:account, :password, :password_confirmation, :role, :name, :available)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/administrators/edit.html.erb
<div class="pageheader">
  <h2><i class="fa fa-cog"></i> 系统管理 <span>创建管理员</span></h2>
</div>
<div class="contentpanel">
  <%= render "commons/error_messages", target: @administrator %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">管理员信息</h4>
    </div>
    <div class="panel-body panel-body-nopadding">
      <%= form_for @administrator, html: { class: 'form-horizontal form-bordered' } do |f| %>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.role' %></label>
          <div class="col-sm-6">
            <%= f.collection_select :role_id, Role.all, :id, :name %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.account' %></label>
          <div class="col-sm-6">
            <%= f.text_field :account, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.name' %></label>
          <div class="col-sm-6">
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'setting' %></label>
          <div class="col-sm-6">
            <div class="ckbox ckbox-default mt5">
              <%= f.check_box :available %>
              <label for="administrator_available"><%= brac_t 'administrator.available' %></label>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-12 text-center">
            <%= f.submit '提交', class: 'btn btn-primary' %>&nbsp;
            <input type="reset" value="重置" class="btn" />
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/administrators/index.html.erb
<div class="pageheader">
  <h2><i class="fa fa-cog"></i> 系统管理 <span>管理员列表</span></h2>
</div>
<div class="contentpanel">
  <%= brac_flash %>
  <div class="row">
    <div class="col-md-12">
      <div class="table-responsive">
        <table class="table table-striped mb30">
          <thead>
            <tr>
              <th><%= brac_t 'administrator.role' %></th>
              <th><%= brac_t 'administrator.account' %></th>
              <th><%= brac_t 'administrator.name' %></th>
              <th><%= brac_t 'administrator.available' %></th>
              <th></th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <td colspan="5"><%= brac_paginate @administrators %></td>
            </tr>
          </tfoot>
          <tbody>
            <% @administrators.each do |administrator| %>
            <tr>
              <td><%= administrator.role.name %></td>
              <td><%= administrator.account %></td>
              <td><%= administrator.name %></td>
              <td><%= brac_styled_boolean administrator.available? %></td>
              <td class="table-action">
                <%= link_to raw('<i class="fa fa-file-text-o"></i>'), administrator %>
                <%= link_to raw('<i class="fa fa-pencil"></i>'), edit_administrator_path(administrator) %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/administrators/new.html.erb
<div class="pageheader">
  <h2><i class="fa fa-cog"></i> 系统管理 <span>创建管理员</span></h2>
</div>
<div class="contentpanel">
  <%= render "commons/error_messages", target: @administrator %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">管理员信息</h4>
    </div>
    <div class="panel-body panel-body-nopadding">
      <%= form_for @administrator, html: { class: 'form-horizontal form-bordered' } do |f| %>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.role' %></label>
          <div class="col-sm-6">
            <%= f.collection_select :role_id, Role.all, :id, :name %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.account' %></label>
          <div class="col-sm-6">
            <%= f.text_field :account, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.name' %></label>
          <div class="col-sm-6">
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.password' %></label>
          <div class="col-sm-6">
            <%= f.text_field :password, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.password_confirmation' %></label>
          <div class="col-sm-6">
            <%= f.text_field :password_confirmation, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'setting' %></label>
          <div class="col-sm-6">
            <div class="ckbox ckbox-default mt5">
              <%= f.check_box :available %>
              <label for="administrator_available"><%= brac_t 'administrator.available' %></label>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-12 text-center">
            <%= f.submit '提交', class: 'btn btn-primary' %>&nbsp;
            <input type="reset" value="重置" class="btn" />
          </div>
        </div>
      <% end %>
      <% content_for :javascript do %>
        <script>
          jQuery(document).ready(function(){
            $('#administrator_role_id').chosen({'width': '100%', 'white-space': 'nowrap'});
          });
        </script>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/administrators/show.html.erb
<div class="pageheader">
  <h2><i class="fa fa-cog"></i> 系统管理 <span>查看管理员</span></h2>
</div>
<div class="contentpanel">
  <%= brac_flash %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">管理员信息</h4>
    </div>
    <div class="panel-body panel-body-nopadding">
      <%= form_tag nil, class: 'form-horizontal form-bordered' do %>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.role' %></label>
          <div class="col-sm-6">
            <%= text_field_tag nil, @administrator.role.name, readonly: true, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.account' %></label>
          <div class="col-sm-6">
            <%= text_field_tag nil, @administrator.account, readonly: true, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.name' %></label>
          <div class="col-sm-6">
            <%= text_field_tag nil, @administrator.name, readonly: true, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.available' %></label>
          <div class="col-sm-6">
            <div class="mt5"><%= brac_styled_boolean @administrator.available? %></div>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.last_signined_at' %></label>
          <div class="col-sm-6">
            <%= text_field_tag nil, brac_datetime(@administrator.last_signined_at), readonly: true, class: 'form-control' %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="panel-footer">
      <%= link_to '返回管理员列表', administrators_path, class: 'btn btn-default' %>&nbsp;
      <%= link_to '编辑', edit_administrator_path(@administrator), class: 'btn btn-default' %>&nbsp;
    </div>
  </div>
</div>

app/views/admin/profiles/edit.html.erb
<div class="pageheader">
  <h2><i class="fa fa-tags"></i> 我的信息</h2>
</div>
<div class="contentpanel">
  <%= brac_flash %>
  <%= render "commons/error_messages", target: @administrator %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">编辑个人信息</h4>
    </div>
    <div class="panel-body panel-body-nopadding">
      <%= form_for @administrator, url: profile_path, html: { class: 'form-horizontal form-bordered' } do |f| %>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.role' %></label>
          <div class="col-sm-6">
            <%= text_field_tag nil, @administrator.role.name, readonly: true, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.account' %></label>
          <div class="col-sm-6">
            <%= text_field_tag nil, @administrator.account, readonly: true, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.name' %></label>
          <div class="col-sm-6">
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-12 text-center">
            <%= f.submit '提交', class: 'btn btn-primary' %>&nbsp;
            <input type="reset" value="重置" class="btn" />
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/profiles/edit_password.html.erb
<div class="pageheader">
  <h2><i class="fa fa-tags"></i> 我的信息</h2>
</div>
<div class="contentpanel">
  <%= brac_flash %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">修改密码</h4>
    </div>
    <div class="panel-body panel-body-nopadding">
      <%= form_tag update_password_profile_path, class: 'form-horizontal form-bordered' do %>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.original_password' %></label>
          <div class="col-sm-6">
            <%= password_field_tag :orginal_password, nil, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.new_password' %></label>
          <div class="col-sm-6">
            <%= password_field_tag :new_password, nil, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.password_confirmation' %></label>
          <div class="col-sm-6">
            <%= password_field_tag :password_confirmation, nil, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-12 text-center">
            <%= submit_tag '提交', class: 'btn btn-primary' %>&nbsp;
            <input type="reset" value="重置" class="btn" />
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <title>JustDrink ManagementSystem</title>
  <%= stylesheet_link_tag 'admin', media: 'all' %>
  <!--[if lt IE 9]>
  <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
<div id="preloader">
    <div id="status"><i class="fa fa-spinner fa-spin"></i></div>
</div>
<section>
  <div class="leftpanel">
    <div class="logopanel">
        <h1><span>[</span> JustDrink <span>]</span></h1>
    </div>
    <div class="leftpanelinner">    
      <h5 class="sidebartitle">Match Navigation</h5>
      <ul class="nav nav-pills nav-stacked nav-bracket">
        <li class="nav-parent"><a href=""><i class="fa fa-bullhorn"></i> <span>分类管理</span></a>
          <ul class="children">
            <li><%= link_to raw('<i class="fa fa-caret-right"></i> 分类列表'), admin_categories_path %></li>
            <li><%= link_to raw('<i class="fa fa-caret-right"></i> 创建新分类'), new_admin_category_path %></li>
          </ul>
        </li>
        <li class="nav-parent"><a href=""><i class="fa fa-cog"></i> <span>系统管理</span></a>
          <ul class="children">
            <li><%= link_to raw('<i class="fa fa-caret-right"></i> 管理员列表'), admin_users_path %></li>
            <li><%= link_to raw('<i class="fa fa-caret-right"></i> 创建新管理员'), new_admin_user_path %></li>
            <li><%= link_to raw('<i class="fa fa-caret-right"></i> 错误列表'), admin_errors_path %></li>
          </ul>
        </li>
      </ul>
      <div class="infosummary">
        <h5 class="sidebartitle">Information Summary</h5>    
        <ul>
          <li>
            <div class="datainfo">
              <span class="text-muted">今日访问量</span>
              <h4>526</h4>
            </div>
            <div id="sidebar-chart" class="chart"></div>   
          </li>
          <li>
            <div class="datainfo">
              <span class="text-muted">版本数</span>
              <h4>618</h4>
            </div>
            <div id="sidebar-chart2" class="chart"></div>   
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="mainpanel">
    <div class="headerbar">
      <a class="menutoggle"><i class="fa fa-bars"></i></a>
      <div class="header-right">
        <ul class="headermenu">
          <li>
            <div class="btn-group">
              <button class="btn btn-default dropdown-toggle tp-icon" data-toggle="dropdown">
                <i class="glyphicon glyphicon-envelope"></i>
                <span class="badge">0</span>
              </button>
              <div class="dropdown-menu dropdown-menu-head pull-right">
                <h5 class="title">您有0条未读消息</h5>
                <ul class="dropdown-list gen-list">
                  <!--li class="new">
                    <a href="">
                    <span class="thumb"><img src="images/photos/user1.png" alt="" /></span>
                    <span class="desc">
                      <span class="name">Draniem Daamul <span class="badge badge-success">new</span></span>
                      <span class="msg">Lorem ipsum dolor sit amet...</span>
                    </span>
                    </a>
                  </li-->
                  <li class="new"><a href="">查看所有消息</a></li>
                </ul>
              </div>
            </div>
          </li>
          <li>
            <div class="btn-group">
              <button class="btn btn-default dropdown-toggle tp-icon" data-toggle="dropdown">
                <i class="glyphicon glyphicon-exclamation-sign"></i>
                <span class="badge">0</span>
              </button>
              <div class="dropdown-menu dropdown-menu-head pull-right">
                <h5 class="title">您有0条未读通知</h5>
                <ul class="dropdown-list gen-list">
                  <!--li class="new">
                    <a href="">
                    <span class="thumb"><img src="images/photos/user4.png" alt="" /></span>
                    <span class="desc">
                      <span class="name">Zaham Sindilmaca <span class="badge badge-success">new</span></span>
                      <span class="msg">is now following you</span>
                    </span>
                    </a>
                  </li-->
                  <li class="new"><a href="">查看所有通知</a></li>
                </ul>
              </div>
            </div>
          </li>
          <li>
            <div class="btn-group">
              <button class="btn btn-default dropdown-toggle tp-icon" data-toggle="dropdown">
                <span class="small">欢迎您，<%= session[:user][:name] %></span>
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu dropdown-menu-usermenu pull-right">
                <li><%= link_to raw('<i class="glyphicon glyphicon-user"></i> 我的信息'), edit_admin_profile_path %></li>
                <li><%= link_to raw('<i class="glyphicon glyphicon-cog"></i> 修改密码'), edit_password_admin_profile_path %></li>
                <li><%= link_to raw('<i class="glyphicon glyphicon-log-out"></i> 退出登录'), admin_signout_path %></li>
              </ul>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <%= yield %>
  </div>
</section>
<%= javascript_include_tag 'admin' %>
<%= content_for :javascript %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hyacinth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>